### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by atsalyuk** [JOHNEPPILLAR/arlo#11]
I've been trying to play around with this and have had issues getting the login stuff working. I haven't been able to log in successfully using a token or using the email method. Is it working for anyone else or is there something I'm missing?

**Comment by JOHNEPPILLAR** [comment]
> I've been trying to play around with this and have had issues getting the login stuff working. I haven't been able to log in successfully using a token or using the email method. Is it working for anyone else or is there something I'm missing?

Hi,

Couple of things to help debug this for you:

1. For email auth: Is your email service imap enabled?
2. Can you add the following debug arg before running your node app and share the output:        export DEBUG="Arlo:*"
