### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Jbone187** [JOHNEPPILLAR/arlo#20]
**Describe the bug**

**To Reproduce**
When I run script I get a 6 digit code send to my email and I am unable to login. I am using imap

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JOHNEPPILLAR** [comment]
> 

Hi, thanks for raising an issue. To help me understand what is going wrong can you share any error messages you get. You can turn on debug by using export DEBUG="Arlo:*" before running your node app. Also it would be helpful to know which method you are using email for example. And if email do you have MFA turned on.
